spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chippy?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qwertyui

logging:
  level:
    com.piglet.shop.mapper: DEBUG

redis:
  host: 127.0.0.1
  #password: qwerty