spring:
  profiles:
    active: dev
  application:
    name: shop-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
redis:
  pool:
    maxActive: 300
    maxIdle: 10
    maxWait: 1000
  port: 6379
  timeout: 2000
  sysName: chippy-blog
  enable: true
  database: 0

mybatis:
  basepackage: top.chippy.blog.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8080

jwt:
  token-header: Authorization
  expire: 1296000000
  rsa-secret: 123456

logging:
  level:
    top.chippy.blog: debug