spring:
  datasource:
    url: jdbc:mysql://192.168.1.163:3306/chippy?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qwertyui
    redis:
      host: 192.168.1.165
      port: 6379
      jedis:
        pool:
          max-active: 10
          min-idle: 6
          max-idle: 8
      password: qwerty

logging:
  level:
    com.piglet.shop.mapper: DEBUG

redis:
  host: 192.168.1.165
  password: qwerty